apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mysecret2
  namespace: default
spec:
  encryptedData:
    git_repo: AgAj+aYa0vEa8dVogyqKEjCzuMXX46JEyGVv8hhsi4MpF6TxhxzdTu4/uInfxX9lTOFSDQBrGLwFz0+tOG3u9E0hizTkyMX061sMtTKoGZdsqDgp8lgG995Ni9c92n/QFrfKsUQfH89IAO/Dv28voU7lL1RDu1h5MUBOOfY3cgNX9+QknFmwpjvaYFEfqvR7IHnG0sIYshnI3HVrzudfqJn14ijZjrtJGmYijHmUEODB5hpSm/eJ51Lz2g1Mz4PYhjjko0PtdULVZTJKHdKPoGH38cJBoixFSHMCQyNoA/vQ0RzrQpQG2XWnutck48Q1w79rFTnU+Ni/fD1qQwhE0eJn0t5NYNRT/q7W9YU4gvOz5zxg8nqvIrqtnHtCuo7cTtijDduU7GW55jwJeyo/2dCPYXMSSsqGdHXXOA7wvJecyc24t2NAPy1V+Qo7ZOX3pYGXx50gRx3xSxdCUs9qUM/8fNdTJuar94r0fHmtlzvKt+dxuXungXMU032r9g3vA8X4emKszmAWfoqitDEuOoUopHIa942AJpXuTqqfDuDVzHWrFA6LVE9/6U6wWoqd76sZHNiLDlBe/NgV/KHkKq10g6a0YRm1kMM9kr4A1CtfL1KMhxDdAN2tLh25yptop1VJwZKodUhZ9Z2hdnFOj6SufYhd/ev718rW8kJM94Lhg5dN/SXFSr7lOWjK1xGVanG0mM6DsaOn9gm5cI5TC6qsoMz2Wt0lcU2+bE4ZYzqc5FJnnfEiGnqb9HI=
    git_token: AgC65BXinn7SkQEJwoF5l88y6jtiJ46a99Wa4TL3RCUEep90W7DO5avkzMJjXy4Jb7vuQIvs7bjIQYGw4WlUChN04G+GDz01mqt0byI90ffqCIRqccDBvtvs6t3lZyh4x0P461gY8yfRuo7qgqDWKQUGFuxgMoeriRFfFFK7aOii4b0i1BRE9x2LiaMT8GPcy9SuB0epBHxJPNzXmNztJA+BhUF7AO6Sy/Ya3Q7+wTQf3aepuwzgyFqYvigT8PUwTYUnpSXGBfpRK7O+Bml752bC7704jrhFD7patZeFIEh/TyFmYNXYgHvRlQaLcpxzHgIs9aSgxLMadxem4s+Tj3ChBm3DdHhFpxAVf5X2+yZ5b4DOPXIcxMPlcIhd577dcAYDPVcn9PbyTbsNNo6IMfKA+O6Jk7gJuTW7QlwjnwJQE5rAjJ2cYpqbuBPYvnFuEmACPKGmcW4k6DkMn1kghTZkTXVZibXr9caF1woAtXPZ8uQQL199gG6MQRDK8kUiTZ9CIdo5jB2bH7en+jbOECdrvJtiOFFxaRiAfVfj1KrSq2LaqzmX47QIZBibjQ1gCZ1ogGXE/7kUeY0oIODgMqBKG9p4uW9bnkyZ810bNJUwE/TzTmJ+bRKHU4jaI1rxnqaWdZmSx8vePKDTtd0SnFzBNXrHRkeqpMhZ4OTrF+KTaJ/Ue/EaC0s29Lxe5pzAYqNSL9PUQPvlA+RYBNrhX34=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: mysecret2
      namespace: default

